# Generated by Django 3.2.4 on 2021-06-23 15:58

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField(verbose_name=builtins.max)),
                ('date', models.DateField()),
            ],
        ),
    ]
